import { exotic_biomes } from "./lists";

/**
 * An object that maps unique biome descriptors to their more general biome type.
 */
export const biomeDescriptorMap: { [index: string]: string } = {
  "[REDACTED]": "Chromatic",
  Acidic: "Toxic",
  Acrid: "Toxic",
  Airless: "Dead",
  Arctic: "Frozen",
  Arid: "Scorched",
  "Ash-Shrouded": "Volcanic",
  Ashen: "Volcanic",
  Azure: "Chromatic",
  Barren: "Barren",
  Basalt: "Volcanic",
  Bladed: "Irri Shells",
  Bleak: "Barren",
  Blighted: "Toxic",
  Blood: "Chromatic",
  Boggy: "Marsh",
  Boiling: "Scorched",
  "Boiling Doom": "Infested Scorched",
  Bountiful: "Lush",
  Breached: "Beams",
  Bubbling: "Bubble",
  Cabled: "Contour",
  Calcified: "M Structure",
  Capped: "Hydro Garden",
  Caustic: "Toxic",
  "Caustic Nightmare": "Infested Toxic",
  Cerulean: "Chromatic",
  Charred: "Scorched",
  "Chromatic Fog": "Chromatic",
  Cloudy: "Marsh",
  Columned: "Shards",
  Contaminated: "Irradiated",
  Corrosive: "Toxic",
  Contoured: "Contour",
  Crimson: "Chromatic",
  Damp: "Marsh",
  Dead: "Dead",
  "Deathly Green Anomaly": "Chromatic",
  "Decaying Nuclear": "Irradiated",
  Desert: "Barren",
  Doomed: "Glitch",
  "Doomed Jade": "Chromatic",
  Dusty: "Barren",
  Empty: "Dead",
  "Endless Morass": "Marsh",
  Erased: "Glitch",
  Erupting: "Volcanic",
  Fiery: "Scorched",
  "Fiery Dreadworld": "Infested Scorched",
  Finned: "Irri Shells",
  Fissured: "Beams",
  "Flame-Ruptured": "Volcanic",
  Flourishing: "Lush",
  Foaming: "Bubble",
  Foggy: "Marsh",
  Forsaken: "Dead",
  Fractured: "Wire Cell",
  Fragmented: "Wire Cell",
  Freezing: "Frozen",
  Frostbound: "Frozen",
  Frothing: "Bubble",
  Frozen: "Frozen",
  "Frozen Anomaly": "Chromatic",
  "Frozen Hell": "Infested Frozen",
  Fungal: "Hydro Garden",
  "Gamma-Intensive": "Irradiated",
  Glacial: "Frozen",
  Glassy: "Glitch",
  Grassy: "Lush",
  "Harsh Blue Globe": "Chromatic",
  "Haunted Emeril": "Chromatic",
  Hazy: "Marsh",
  Hexagonal: "Hexagon",
  Hiemal: "Frozen",
  "High Energy": "Irradiated",
  "High Radio Source": "Irradiated",
  "High Temperature": "Scorched",
  Hot: "Scorched",
  Humid: "Lush",
  Hyperborean: "Frozen",
  Icebound: "Frozen",
  Icy: "Frozen",
  "Icy Abhorrence": "Infested Frozen",
  "Imminent Core Detonation": "Volcanic",
  Incandescent: "Scorched",
  Infected: "Glitch",
  "Infected Dustbowl": "Infested Barren",
  "Infested Paradise": "Infested Lush",
  Irradiated: "Irradiated",
  Isotopic: "Irradiated",
  Lava: "Volcanic",
  "Life-Incompatible": "Dead",
  Lifeless: "Dead",
  "Lost Blue": "Chromatic",
  "Lost Green": "Chromatic",
  "Lost Red": "Chromatic",
  "Low Atmosphere": "Dead",
  Magma: "Volcanic",
  Malfunctioning: "Glitch",
  Marshy: "Marsh",
  Mechanical: "Fract Cube",
  Metallic: "Fract Cube",
  Metallurgic: "Fract Cube",
  Miasmatic: "Toxic",
  Misty: "Marsh",
  Molten: "Volcanic",
  Murky: "Marsh",
  Mutated: "Infested Irradiated",
  Noxious: "Toxic",
  Nuclear: "Irradiated",
  "Obsidian Bead": "Volcanic",
  "of Light": "Beams",
  Ossified: "M Structure",
  Overgrown: "Lush",
  Paradise: "Lush",
  Parched: "Barren",
  Petrified: "M Structure",
  Pillared: "Shards",
  "Planetary Anomaly": "Chromatic",
  Plated: "Hexagon",
  Poisonous: "Toxic",
  Quagmire: "Marsh",
  Radioactive: "Irradiated",
  "Radioactive Abomination": "Infested Irradiated",
  Rainy: "Lush",
  Rattling: "Bone Spire",
  Reeking: "Marsh",
  Rocky: "Barren",
  Rotting: "Toxic",
  Scalding: "Scorched",
  Scaly: "Hexagon",
  Scarlet: "Chromatic",
  Scorched: "Scorched",
  Sharded: "Shards",
  Shattered: "Wire Cell",
  "Shell-Strewn": "Irri Shells",
  Skeletal: "Bone Spire",
  Spined: "Bone Spire",
  Sporal: "Hydro Garden",
  "Stellar Corruption Detected": "Chromatic",
  "Sub-zero": "Frozen",
  Supercritical: "Irradiated",
  Swamp: "Marsh",
  Tainted: "Infested Barren",
  Tectonic: "Volcanic",
  Temperate: "Lush",
  Temporary: "Glitch",
  "Terraforming Catastrophe": "Dead",
  Terrorsphere: "Infested Barren",
  "The Nest": "Infested Lush",
  Thirsty: "Glitch",
  Torrid: "Scorched",
  Toxic: "Toxic",
  "Toxic Anomaly": "Chromatic",
  "Toxic Horror": "Infested Toxic",
  Ultramarine: "Chromatic",
  Unstable: "Volcanic",
  Vapour: "Marsh",
  Verdant: "Lush",
  "Vermillion Globe": "Chromatic",
  "Vile Anomaly": "Chromatic",
  Violent: "Volcanic",
  Viridescent: "Lush",
  Volcanic: "Volcanic",
  Webbed: "Contour",
  "Wind-swept": "Barren",
  "Wine Dark": "Chromatic",
  "Worm-Ridden": "Infested Lush",
  "Xeno-Colony": "Infested Lush",
};

/**
 * An object that maps the non-unique biome descriptors to their possible biome types.
 */
export const specialDescriptorMap: { [index: string]: string[] } = {
  Abandoned: ["Barren", "Dead"],
  Desolate: ["Barren", "Dead"],
  Corrupted: ["Glitch", "Infested Scorched"],
  Infested: ["Infested Barren", "Infested Frozen", "Infested Toxic", "Infested Irradiated", "Infested Scorched"],
  Tropical: ["Lush", "Marsh"],
};

/**
 * Marsh can have either "None" or "Star Bulb"
 *    and thus needs to be checked separately
 *
 * Anything other biome must have "None" as their agricultural resource
 */
export const biomeAgriculturalResourceMap: { [index: string]: string } = {
  Barren: "Cactus Flesh",
  Dead: "None",
  Frozen: "Frost Crystal",
  Irradiated: "Gamma Root",
  Lush: "Star Bulb",
  Scorched: "Solanium",
  Toxic: "Fungal Mould",
  Volcanic: "None",
  "Infested Barren": "Cactus Flesh",
  "Infested Frozen": "Frost Crystal",
  "Infested Irradiated": "Gamma Root",
  "Infested Lush": "Star Bulb",
  "Infested Scorched": "Solanium",
  "Infested Toxic": "Fungal Mould",
};

/**
 * An object to speed up verifying if resource and infested biome match.
 */
export const infestedAgriculturalResourceMap: { [index: string]: string } = {
  "Cactus Flesh": "Infested Barren",
  "Frost Crystal": "Infested Frozen",
  "Fungal Mold": "Infested Toxic",
  "Gamma Root": "Infested Irradiated",
  Solanium: "Infested Scorched",
};

/**
 * An object that maps resources to the biomes they can be found in.
 *
 * Cobalt, Magnetized Ferrite, Salt, Silver, and Sodium can be found in any biome.
 */
export const resourceBiomeMap: { [index: string]: string[] } = {
  Ammonia: ["Toxic", "Chromatic", "Infested Toxic"],
  Basalt: ["Volcanic"],
  Dioxite: ["Frozen", "Chromatic", "Infested Frozen"],
  Faecium: ["Marsh"],
  Gold: [...exotic_biomes],
  Mordite: ["Marsh"],
  Paraffinium: ["Lush", "Marsh", "Infested Lush"],
  Phosphorus: ["Scorched", "Chromatic", "Infested Scorched"],
  Pyrite: ["Barren", "Volcanic", "Infested Barren"],
  "Rusted Metal": ["Dead"],
  Uranium: ["Irradiated", "Infested Irradiated"],
};

/**
 * An object that maps system economic type descriptors
 *    to the type of the economy they represent
 */
export const econTypeMap: { [index: string]: string } = {
  Alchemical: "Advanced Materials",
  "Black Market": "Outlaw",
  Commercial: "Trading",
  Construction: "Manufacturing",
  "Energy Supply": "Power Generation",
  Engineering: "Technology",
  Experimental: "Scientific",
  "Fuel Generation": "Power Generation",
  "High Tech": "Technology",
  "High Voltage": "Power Generation",
  Industrial: "Manufacturing",
  Manufacturing: "Manufacturing",
  "Mass Production": "Manufacturing",
  "Material Fusion": "Advanced Materials",
  Mathematical: "Scientific",
  Mercantile: "Trading",
  "Metal Processing": "Advanced Materials",
  Minerals: "Mining",
  Mining: "Mining",
  "Nano-construction": "Technology",
  None: "Uncharted",
  "Ore Extraction": "Mining",
  "Ore Processing": "Advanced Materials",
  "Power Generation": "Power Generation",
  Prospecting: "Mining",
  Research: "Scientific",
  Scientific: "Scientific",
  Shipping: "Trading",
  Technology: "Technology",
  Trading: "Trading",
};

/**
 * An object that maps system economic state descriptors
 *    to the strength of the economy
 *
 * econStrengthMap["Booming"] = "Strong"
 */
export const econStrengthMap: { [index: string]: string } = {
  Adequate: "Average",
  Advanced: "Strong",
  Affluent: "Strong",
  Balanced: "Average",
  Booming: "Strong",
  Comfortable: "Average",
  Declining: "Weak",
  Destitute: "Weak",
  Developing: "Average",
  Failing: "Weak",
  Fledgling: "Weak",
  Flourishing: "Strong",
  "High Supply": "Strong",
  "Low Supply": "Weak",
  "Medium Supply": "Average",
  None: "None",
  Opulent: "Strong",
  Promising: "Average",
  Prosperous: "Strong",
  Satisfactory: "Average",
  Struggling: "Weak",
  Sustainable: "Average",
  Unpromising: "Weak",
  Unsuccessful: "Weak",
  Wealthy: "Strong",
};

/**
 * An object that hold lists of each type of resource
 */
export const resources = {
  agricultural: ["None", "Cactus Flesh", "Frost Crystal", "Fungal Mould", "Gamma Root", "Solanium", "Star Bulb"],
  stellar: [
    "Copper",
    "Activated Copper",
    "Cadmium",
    "Activated Cadmium",
    "Emeril",
    "Activated Emeril",
    "Indium",
    "Activated Indium",
  ],
  local: [
    "Ammonia",
    "Basalt",
    "Dioxite",
    "Faecium",
    "Gold",
    "Mordite",
    "Paraffinium",
    "Phosphorus",
    "Pyrite",
    "Rusted Metal",
    "Uranium",
  ],
  general: ["Cobalt", "Magnetized Ferrite", "Salt", "Silver", "Sodium"],
};

/**
 * An object that hold lists of each type of economy info
 */
export const economy = {
  descriptors: [
    "Alchemical",
    "Black Market",
    "Commercial",
    "Construction",
    "Energy Supply",
    "Engineering",
    "Experimental",
    "Fuel Generation",
    "High Tech",
    "High Voltage",
    "Industrial",
    "Manufacturing",
    "Mass Production",
    "Material Fusion",
    "Mathematical",
    "Mercantile",
    "Metal Processing",
    "Minerals",
    "Mining",
    "Nano-construction",
    "None",
    "Ore Extraction",
    "Ore Processing",
    "Power Generation",
    "Prospecting",
    "Research",
    "Scientific",
    "Shipping",
    "Technology",
    "Trading",
  ],
  types: [
    "Advanced Materials",
    "Manufacturing",
    "Mining",
    "Outlaw",
    "Power Generation",
    "Scientific",
    "Technology",
    "Trading",
    "Uncharted",
  ],
  states: [
    "Adequate",
    "Advanced",
    "Affluent",
    "Balanced",
    "Booming",
    "Comfortable",
    "Declining",
    "Destitute",
    "Developing",
    "Failing",
    "Fledgling",
    "Flourishing",
    "High Supply",
    "Low Supply",
    "Medium Supply",
    "None",
    "Opulent",
    "Promising",
    "Prosperous",
    "Satisfactory",
    "Struggling",
    "Sustainable",
    "Unpromising",
    "Unsuccessful",
    "Wealthy",
  ],
  strengths: ["None", "Weak", "Average", "Strong"],
};
